### ISSUE TITLE
[devops] Deploying to GitHub Pages with TravisCI

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#151]
https://docs.travis-ci.com/user/deployment/pages/

The official example of the `.travis.yml` configuration file.

```
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
```
