### ISSUE TITLE
[devops] Deploying to PyPI with TravisCI

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#153]
https://docs.travis-ci.com/user/deployment/pypi/

Example `.travis.yml`:

```
deploy:
  provider: pypi
  user: ...
  password: ...
  on:
    tags: true
```
