### ISSUE TITLE
[virtualization][kubernetes_development] Run a Job on every Node in the cluster

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#582]
Example:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: hosts-file-update
  namespace: default
  labels:
    app: hosts-file-update
spec:
  # Change these two values to the number of Nodes in the Kubernetes cluster.
  completions: 6
  parallelism: 6
  template:
    metadata:
      name: pod-hosts-file-update
      labels:
        app: hosts-file-update
        hasDNS: "false"
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hosts-file-update
            topologyKey: kubernetes.io/hostname
      containers:
        - name: busybox
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - 'echo "192.168.1.123    foobar.tld" >> /mnt/etc/hosts'
          securityContext:
            privileged: true
          volumeMounts:
             - name: root-filesystem
                mountPath: /mnt
      volumes:
         - name: root-filesystem
            hostPath:
              path: /
      restartPolicy: OnFailure
```

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#always-co-located-in-the-same-node
