### ISSUE TITLE
[virtualization][kubernetes_administration] Use Longhorn for distributed storage

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#583]
Longhorn sets up distributed NFS servers across the Kubernetes cluster. It is made by Rancher.

https://longhorn.io/docs/1.2.2/
https://longhorn.io/docs/1.2.2/deploy/install/install-with-helm/

**Comment by LukeShortCloud** [comment]
Install:

- Longhorn currently only supports these file systems: ext4 and XFS.
- These tools are required on all of the Kubernetes nodes that will host Longhorn storage: bash, curl, findmnt, grep, awk, blkid, lsblk, iscsid iscsiadm, and mount.nfs
- Debian:

```
$ sudo apt-get install bash curl grep gawk util-linux open-iscsi nfs-common
```

- Start the iSCSI daemon.

```
$ sudo systemctl enable --now iscsid
```

https://longhorn.io/docs/1.2.2/deploy/install/#installation-requirements

- Install the Helm chart:

```
$ helm repo add longhorn https://charts.longhorn.io
$ helm repo update
$ helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
```

**Comment by LukeShortCloud** [comment]
I tested version 1.1.1 and 1.2.2 of Longhorn (the Helm chart version actually matches the application version). I could not get any of them to work.

**Comment by LukeShortCloud** [comment]
I tested again with Longhorn 1.2.4, Kubernetes 1.20.9, and Debian 10.12. It works perfectly! I tested with their example PVC manifest file:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```

https://rancher.com/docs/k3s/latest/en/storage/
