### ISSUE TITLE
[virtualization][kubernetes_development] How to use Knative Serving

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#614]
The default behavior is to scale to zero when the Pods are not being used. This can be changed by setting a "minScale" annotation. A "target" annotation can be used for what the normal amount of Pods running should be based on metrics.

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
spec:
  runLatest:
    configuration:
       revisionTemplate:
         metadata:
           annotations:
             autoscaling.knative.dev/minScale: "1"
             # This does NOT need to be defined as it is the default autoscaling class.
             # It scales based on concurrency.
             autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
             # For every concurrency of 2 (2 network traffic hits), scale up.
             autoscaling.knative.dev/target: "2"
```

The metric used for scaling is, by default, concurrency (traffic hits). This can be changed to CPU usage.

```
             autoscaling.knative.dev/metric: cpu
             autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
             # For every CPU usage of "10", scale up.
             autoscaling.knative.dev/target: "10"
```

Set a limit for how many Pods the application can scale to.

```
$ kubectl edit podautoscaler <OBJECT>
apiVersion: autoscaling.internal.knative.dev/v1alpha1
kind: PodAutoScaler
metadata:
  annotations:
    autoscaling.knative.dev/maxScale: "10"
```

Rollout 50% of the Pods to use a specific revision.

```
spec:
  release:
    revisions:
      - app-00002
      - app-00003
    rolloutPercent: 50
```

Sources:

- https://www.youtube.com/watch?v=OPSIPr-Cybs
- https://knative.dev/docs/serving/autoscaling/autoscale-go/
