### ISSUE TITLE
[virtualization][kubernetes_development] Create a K8ssandra datacenter

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#800]
Using the Helm chart.

Example:

```
cassandra:
  auth:
    superuser:
      secret: cassandra-admin-secret
  cassandraLibDirVolume:
    storageClass: standard-rwo
  clusterName: mixed-workload
  datacenters:
  - name: dc1
    size: 3
    racks:
    - name: rack1
      affinityLabels:
        failure-domain.beta.kubernetes.io/zone: us-west4-a
    - name: rack2
      affinityLabels:
        failure-domain.beta.kubernetes.io/zone: us-west4-b
    - name: rack3
      affinityLabels:
        failure-domain.beta.kubernetes.io/zone: us-west4-c
```

```
$ helm install txndc k8ssandra/k8ssandra -f dc1.yaml -n txndc
```

https://k8ssandra.io/blog/tutorials/deploy-a-multi-datacenter-apache-cassandra-cluster-in-kubernetes/
