### ISSUE TITLE
[virtualization][kubernetes_development] Update TanzuKubernetesCluster TKC API reference

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#861]
For the new v1alpha2 version. Worker nodes are now defined in a list of node pools. This is helpful for creating specialized node pools. For example, a small pool can have NVIDIA vGPUs allocated to it.

Example:

```
apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-v2-cluster-default
  namespace: tkgs-cluster-ns
spec:
  topology:
    controlPlane:
      replicas: 3
      vmClass: guaranteed-medium
      storageClass: vwt-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-nodepool-a1
      replicas: 3
      vmClass: guaranteed-large
      storageClass: vwt-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
```

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-B2807BCD-0CE1-4C3A-9C0E-2B78F5DA0E90.html
