### ISSUE TITLE
[programming][devops] Only run GitHub Actions workflow on specific branches

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#923]
Examples:

- One or more branches:

```
on:
  push:
    branches:
      - main
      - foobar
```

- On all branches except `main`:

```
on:
  push:
    branches:
      - '*'
      - '!main'
```

https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
